### ISSUE TITLE
Having an issue with installation 

### ISSUE THREAD

**Issue by davin12345678910** [LeeJMorel/PathKit#242]
**Describe the bug**
When trying to install pathkit i get an error message from apple mentioning that "Pathkit" cannot be open because the developer could not be verified 

**To Reproduce**
1. Go to  https://pathkit2e.com/   
2. Click on download
3. Wait for download to complete
4. A file window will pop up
5. click on pathkit
6. error message will pop up 

**Expected behavior**
An error message will pop up mentioning this: "Pathkit" cannot be open because the developer could not be verified 

**Screenshots**

**Desktop (please complete the following information):**
 - IOS macbook, M1 chip 

**Additional context**
N/A

**Comment by LeeJMorel** [comment]
PathKit is an open source student project. As such we do not have the funding to have the software signed by major OS companies like Windows and Apple. Apple alone costs $99-350 per year to sign software with their company for safe downloads. While we understand this presents a security risk to your computer, we follow strict coding practices to prevent malicious code, and the repository is available for complete review.

You can bypass the security issues on mac to download PathKit by following the instructions here: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

I will be closing this issue as we cannot resolve it at this time.
