### ISSUE TITLE
Research possible testing and CI implementations

### ISSUE THREAD

**Issue by LeeJMorel** [LeeJMorel/PathKit#52]
**What MVP does your issue request work on?**
- [ ] Physics based dice roller
- [ ] GM customization options to all input
- [ ] Create Exploration or Encounter modes
- [ ] Add players/NPCS/Beasts/Shops
- [ ] Integrated search engine
- [ ] Notes Feature
- [x] Testing

**Describe the solution you'd like**
3-4 different test suits
1-2 CI implementations researched

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LeeJMorel** [comment]
@Panadero1  This phase is now closed, please either mark done or shift the due date to our next sprint phase. if you change the sprint please explain why the deliverable had to shift its due date (what issues came up? what solutions have you figured out to hopefully prevent this? did this impact other teams? is it partially done or not touched yet?).

**Comment by Panadero1** [comment]
I found testing tools to use, but not CI yet. So I'm pushing this to DNA and working on it as first priority
