### ISSUE TITLE
Define any iconography and logos

### ISSUE THREAD

**Issue by Puggernauts** [LeeJMorel/PathKit#55]
**What MVP does your issue request work on?**
- [ ] Physics based dice roller
- [ ] GM customization options to all input
- [ ] Create Exploration or Encounter modes
- [ ] Add players/NPCS/Beasts/Shops
- [ ] Integrated search engine
- [ ] Notes Feature
- [ ] Documentation & Automation Tools
- [ ] Testing
- [x] UX Design

**Describe the solution you'd like**
We want an assortment of iconography and logos used in the tool

**Describe alternatives you've considered**
2-4 selections to test against HCI feedback

**Additional context**
N/A

**Comment by LeeJMorel** [comment]
@Puggernauts This phase is now closed, please either mark done or shift the due date to our next sprint phase. if you change the sprint please explain why the deliverable had to shift its due date (what issues came up? what solutions have you figured out to hopefully prevent this? did this impact other teams?).

I know you DM'd me about this on slack so I am going to change it this week, but please try to do this at the end of every sprint going forward so we can stay on task.

**Partially Done**
More time needed as this process introduced a new tool system (Figma) which took up a large portion of time to become familiar with. Moved from GPS to DnA sprint.
